[package]
name = "rust-mandlebrotset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.9", features = ["derive"] }
image = "0.24.4"
num = "0.4.0"
progress_bar = "1.0.2"
